### ISSUE TITLE
Disable the blank line inserted at the top of the imports

### ISSUE THREAD

**Issue by dbatten5** [lyz-code/autoimport#148]
## Description
I wasn't sure if this is a bug or a feature, but whenever I run `autoimport` a blank line is inserted above the import statements. 

before running `autoimport`:
![image](https://user-images.githubusercontent.com/17271241/136978544-0b9f6cac-d376-4470-ad53-5e241d1380ce.png)

after running `autoimport`:
![image](https://user-images.githubusercontent.com/17271241/136978639-c9cf0656-a025-47c8-8dcc-f581f4359a1a.png)

## Possible Solution
If this is a feature, it would be great to have a config option to turn it off. If it's a bug, should be as simple as removing whatever is inserting it, I'd be happy to open a PR depending on what needs to be done.

## Additional context
I'm running this from the command line via a vim command: `:!autoimport %`

**Comment by lyz-code** [comment]
Hi @dbatten5 , thank you for taking the time to open the issue and volunteering to do a PR. I'm afraid it's a "feature", `autoimport` parses the source code and divides it into four sections: header, imports, typing, and code. You can see it [here](https://github.com/lyz-code/autoimport/blob/master/src/autoimport/model.py#L183). I thought it was interesting to add a new line between each section to improve readability.

That being said, I'm not against adding a config option to disable this behaviour. Sadly, `autoimport` doesn't yet have that feature implemented, so there is no way to deviate from the standard opinionated workflow. This has been [raised  too in `yamlfix`](https://github.com/lyz-code/yamlfix/issues/117) another fixer I maintain. If you were to make a PR I'd point in that direction.

Ideally for me, `autoimport` could read it's configuration from a section in the `pyproject.toml` project file, to avoid creating new fixer files in the repository, but if you have other ideas, I'm more than open to them.

**Comment by dbatten5** [comment]
hi @lyz-code yeah i think reading from `pyproject.toml` would be a good starting point. i'd be happy to try and implement that and once that's in place could tackle the blank line config option?

**Comment by lyz-code** [comment]
Sounds really good to me :)

**Comment by dbatten5** [comment]
just coming back to this now - i think this is mentioned in the docs as well but typically i just run `black` after `autoimport` which resolves any potential formatting issues. happy to close this issue as i don't really see it as an issue any more

**Comment by lyz-code** [comment]
I'm fine with closing it too, if anyone still sees it as an issue, please
comment here and we'll reopen it.
