### ISSUE TITLE
crashes when processing some imports that have `# comments`

### ISSUE THREAD

**Issue by Jasha10** [lyz-code/autoimport#163]
## Description
`autoimport` crashes when there are multiple imports from the same module and one of the imports is marked with a `# noqa` comment.

## Current behavior
Here is a file that causes a crash:
```python
# tmp.py
from typing import Any  # noqa
from typing import TypeVar
```
Here is the output from `autoimport`:
```text
$ autoimport tmp.py
Traceback (most recent call last):
  File "/home/jasha10/miniconda3/envs/pysc/bin/autoimport", line 8, in <module>
    sys.exit(cli())
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/entrypoints/cli.py", line 21, in cli
    fixed_code = services.fix_files(files, config)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/services.py", line 29, in fix_files
    fixed_source = fix_code(source, config)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/services.py", line 69, in fix_code
    return SourceCode(original_source_code, config=config).fix()
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/model.py", line 62, in fix
    self._fix_flake_import_errors()
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/model.py", line 257, in _fix_flake_import_errors
    self._remove_unused_imports(import_name)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/model.py", line 411, in _remove_unused_imports
    imports.remove(object_name)
ValueError: list.remove(x): x not in list
```

## Desired behavior
Ideally, the noqa line(s) should not be touched, and the other line(s) should be processed as usual.

## Environment
```text
$ autoimport --version
           autoimport version: 0.8.0
               python version: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:23:11)  [GCC 9.4.0]
                     platform: Linux-5.4.0-87-generic-x86_64-with-glibc2.27
```

**Comment by Jasha10** [comment]
I'll try to submit a PR to fix this some time later this week.

**Comment by lyz-code** [comment]
Hey @Jasha10 sorry for the delay these days answering you, I didn't have much time. As always, thank you for your time opening issues and proposing fixes

**Comment by Jasha10** [comment]
My pleasure! It turns out the bug was with comments in general, not with the word `'noqa'` specifically.

What's the desired behavior for lines that have comments?
For example: I was able to get the following test case working by modifying `autoimport`'s regex patterns:
```python
    source = dedent(
        """\
        import os  # comment 1
        import sys  # comment 2

        os.getcwd()
        """
    )
    desired_source = dedent(
        """\
        import os  # comment 1
        # comment 2

        os.getcwd()
        """
    )
```
BUT, I'm not sure if preserving comment2 like that is desirable. For example, the user might have made a comment about the import, and now the comment makes no sense since the import is gone.

@lyz-code, what do you think is the best behavior for comments on imports that would be removed?

**Comment by lyz-code** [comment]
I'd vote to remove them. If someone complains in the future about this behaviour, we can always add a configuration option to prevent them to be removed. What did you have in mind?

**Comment by Jasha10** [comment]
Removing them sounds good to me!

**Comment by lyz-code** [comment]
Hey @Jasha10 , I've been working on this issue.

The original issue was the use of `noqa`. `autoimport` only ignores the lines that have `noqa: autoimport`, so the next snippet works:

```python
    source = dedent(
        """\
        # tmp.py
        from typing import Any  # noqa: autoimport
        from typing import TypeVar
        """
    )
    desired_source = dedent(
        """\
        # tmp.py

        from typing import Any  # noqa: autoimport
        """
    )
```

I think it's interesting to specify what kind of `noqa` you want to use, is very cumbersome for you to write the `: autoimport`?

I've also fixed the removal of the comment on simple import statements, on multiline will still fail, but I'm not sure it's a common case. If it is, whenever it occurs we can open another issue.

It should work on `0.9.0`, if it doesn't please reopen the issue

**Comment by Jasha10** [comment]
Awesome, thanks for taking on the implementation :)
