### ISSUE TITLE
Support a config file with example imports

### ISSUE THREAD

**Issue by HoverHell** [lyz-code/autoimport#169]
## Description
It would be useful to support local conventions (such as `import datetime as dt`) and names from local modules (`from mymodule.mypackage.somewhere import SomeName`).

## Possible Solution
Doing this requires a config; a most simple config for this would be a `py` file with example imports.

Example implementation: https://github.com/lyz-code/autoimport/pull/170

## Additional context
For further consideration: an extra tool for gathering all imports from files, to build such config, to cleanup, tune, and use it.

## Related Issue
Can be seen as an alternative to https://github.com/lyz-code/autoimport/issues/39

**Comment by lyz-code** [comment]
Hi @HoverHell , thank you for taking the time to open an issue. Recently @Jasha10 [added support for local configuration](https://github.com/lyz-code/autoimport/issues/159), it has been documented [here](https://lyz-code.github.io/autoimport/#configuration), please take a look and tell me if this will fulfill your use case

**Comment by HoverHell** [comment]
I can work around it, with a wrapper like this: https://gist.github.com/HoverHell/b479c566960d91284999f60969bc30f1

However, at the very least that would require config path argument.

**Comment by lyz-code** [comment]
Adding the `--config-file` flag makes sense, but sorry, I still don't understand why would you need a wrapper. Can you help me understand what's missing in the current implementation?

If we add the `--config-file` may I close the [other PR you created](https://github.com/lyz-code/autoimport/pull/170)?

**Comment by HoverHell** [comment]
> why would you need a wrapper

It's still missing a global (home-dir) config.

> may I close the other PR you created

yes

**Comment by Jasha10** [comment]
+1 for a `--config-file` flag :)

**Comment by Jasha10** [comment]
@HoverHell, by a global (home-dir) config, you mean something like `$HOME/.autoimport.toml`?

**Comment by HoverHell** [comment]
Yes (or, better yet, a `~/.config/autoimport/config.toml`) that would be
read by default (unless an extra flag like `--disable-global-config` is
specified).

**Comment by lyz-code** [comment]
The `--config-file` flag is available since `0.10.0`, thanks @HoverHell ! :)

I see now what you mean, and it makes sense too. The loading of the variables would be in order of preference:

* `pyproject.toml` of the repository
* Global config in `~/.config/autoimport/config.toml`
* Autoimport defaults.

I'm closing #170 as it no longer applies. But if you want to make a PR with the global config, I'll be happy to merge it

**Comment by HoverHell** [comment]
> PR with the global config

-> https://github.com/lyz-code/autoimport/pull/172

**Comment by lyz-code** [comment]
Available since `1.2.0` thanks to @Jasha10 who did a PR based on the work of @HoverHell and the awesome `maison` library by @dbatten5
