### ISSUE TITLE
Do not reformat code lines that end with `# fmt: skip`

### ISSUE THREAD

**Issue by superDross** [lyz-code/autoimport#182]
## Description

There is currently no way to tell both black and autoimport to ignore formatting a line.

This can be an issue when using black along with autoimport but wanting both formatters to ignore a debugger line.

The `# noqa: autoimport` is not recognised by black, so the current implementations does not suffice.

Black uses `# fmt: skip` as an instruction to not format a line.

## Possible Solution

We can utilise this same marker to ensure neither autoimport or black format a given line.

**Comment by lyz-code** [comment]
Available since `1.0.4` thanks for the implementation :)
