### ISSUE TITLE
Import objects by mimicking other modules

### ISSUE THREAD

**Issue by mgaitan** [lyz-code/autoimport#212]
The idea of have a list of "common statements" in the pyproject file seems ok for small project, but it's unmaintainable for large scale ones. 

For instance, I have a project with several subpackages defining different classes (sqlalchemy models) and I would like to be able to autoimport them without needing to declare them explicitly.  
The point is I have plenty other modules where I already imported those classes and I would like just 

So, I guess it could be possible to walk sibling modules (or beyond) and try to find there the any missing object is being imported, in a sake of "automatic" common statements. 

If this idea fits in the project I could try to implement it.

**Comment by lyz-code** [comment]
I just realized that this is a duplicate of #39
