### ISSUE TITLE
[Bug] handling top-level `if TYPE_CHECKING: ...` block

### ISSUE THREAD

**Issue by Jasha10** [lyz-code/autoimport#231]
## Description
`autoimport` does not properly handle top-level use of `if TYPE_CHECKING: ...`

### Case 1:
Run `autoimport` on the following file:
```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    foo = "bar"
```
The output looks like this:
```python
if TYPE_CHECKING:
    foo = "bar"
```

Why did the `from typing ...` import disappear?

### Case 2:
Run `autoimport` on the following file:
```python
if TYPE_CHECKING:
    foo = "bar"
```
The output looks like this:
```python
from typing import TYPE_CHECKING



```

Why did the `if TYPE_CHECKING: ...` block disappear?

### Case 3 (this is expected behavior):

Run `autoimport` on the following file:
```python
from typing import TYPE_CHECKING



```
The output is empty:
```python
```

## Current behavior
Repeatedly running `autoimport` on the file from Case 1 causes the file's contents to completely disappear.

## Desired behavior
`autoimport` should not remove the `if TYPE_CHECKING: ...` block or the related import `from typing ...`.

## Environment
```text
 $ python -c "import autoimport.version; print(autoimport.version.version_info())"
------------------------------------------------------------------
     autoimport: 1.3.1
     Python: 3.9.12
     Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.31
------------------------------------------------------------------
```

**Comment by lyz-code** [comment]
I can reproduce the issue, weird, it doesn't happen in `1.2.3`  nor in `1.3.0`, the bug appeared in `1.3.1` and I have to investigate why did the tests miss this bug.

Thanks for pointing it out. Please until it's fixed use `1.3.0`

**Comment by lyz-code** [comment]
Please @Jasha10 try with `1.3.2`, and sorry for the inconveniences :(

**Comment by Jasha10** [comment]
No problem! It's working well now -- thanks!!
